group=fun.bm.mili
version=26.2-R0.1-SNAPSHOT
mcVersion=26.2
apiVersion=26.2
clipVersion=3.0.18
weightVersion=2.0.15
release=1
# 0 for skip release, 1 for pre-release, 2 for release

foliaRef=57f643f10e0a9d01024773232d38ae666067d593

org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
